services:
  - type: web
    name: ai-workout-planner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn simple_ai_web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 